posibilidades = ["manzana", "banana", "cereza", "dátil", "uva", "fresa", "naranja", "limón", "pera", "kiwi",
           "plátano", "mango", "papaya", "sandía", "piña", "aguacate", "pomelo", "ciruela", "melocotón", "albaricoque",
           "nectarina", "coco", "maracuyá", "mora", "frambuesa", "zarzamora", "mandarina", "lima", "granada", "higo",
           "cambur", "guayaba", "durazno", "caqui", "tamarindo", "membrillo", "uva pasa", "guanábana", "guayabo", "toronja", "cassis", "arándano", "avellana", "almendra", "nuez", "pistacho", "anacardo", "cacahuate", "macadamia", "castaña", "maní", "avocado", "breva", "zapote", "acelga", "achicoria", "apio", "batata","berenjena", "brócoli", "calabacín", "coliflor", "espinaca", "judía", "lenteja", "lechuga", "maíz", "pimiento", "patata", "pepino", "rábano", "tomate", "zanahoria", "cereales", "garbanzo", "alubia", "arroz", "avena", "cebada", "maicena", "quinoa", "trigo", "amaranto", "bulgur", "mijo", "sorgo", "chirimoya", "copoazú", "longan", "rúcula", "endivia", "hinojo", "achote", "culantro", "curry", "ají", "chile", "albahaca", "orégano", "romero", "tomillo", "perejil", "cilantro", "menta", "eneldo", "canela", "cúrcuma", "comino", "mostaza", "nuez moscada", "clavo", "jengibre", "vainilla", "cardamomo", "azúcar",
           "miel", "melaza", "jarabe", "salmón", "atún", "trucha", "merluza", "bacalao", "pejerrey", "sardina", "anguila",
           "calamar", "pulpo", "gambas", "cangrejo", "langosta", "almeja", "mejillón", "ostra", "vieira", "percebe",
           "langostino", "camarón", "caviar", "arenque", "anchoveta", "sardina", "caballa", "boquerón", "anguila", "fletán",
           "rodaballo", "pez espada", "lenguado", "bacalao", "rape", "tiburón", "carpa", "tilapia", "bagre", "anguila", "róbalo",
           "pejelagarto", "tiburón", "tortuga", "caimán", "cocodrilo", "serpiente", "lagarto", "iguana", "gecko", "camaleón",
           "salamanquesa", "anas", "ganso", "pato", "cisne", "pelícano", "flamenco", "grulla", "cigüeña", "avestruz",
           "kiwi", "colibrí", "búho", "halcón", "águila", "gavilán", "halcón", "cuervo", "buitre", "lechuza",
           "abeja", "avispa", "mosquito", "mosca", "mariposa", "polilla", "libélula", "saltamontes", "cucaracha", "hormiga",
           "araña", "escorpión", "tarántula", "ciempiés", "milpiés", "gusano", "lombriz", "caracol", "babosa", "cangrejo",
           "langosta", "camarón", "erizo de mar", "estrella de mar", "pepino de mar", "esponja", "medusa", "coral", "alga", "plancton", "cachalote", "orca", "delfín", "tiburón", "mantarraya", "peces", "pulpo", "calamar", "nautilus",
           "caracol", "tortuga", "cocodrilo", "caimán", "lagarto", "gecko", "serpiente", "boa", "pitón", "víbora",
           "anaconda", "lagarto", "iguana", "camaleón", "salamanquesa", "gecko", "tritón", "salamandra", "rana", "sapo",
           "cangrejo", "cigüeña", "flamenco", "grulla", "pelícano", "cisne", "pato", "ganso", "aguila", "halcón",
           "buitre", "cuervo", "colibrí", "kiwi", "avestruz", "perico", "loro", "cotorra", "gallina", "gallo",
           "pavo", "pavo real", "faisán", "pichón", "paloma", "colomillo", "cucú", "rata", "ratón", "ardilla",
           "conejo", "liebre", "ciervo", "caballo", "yegua", "potro", "asno", "mula", "burro", "cebra",
           "elefante", "rinoceronte", "hipopótamo", "jirafa", "camello", "dromedario", "llama", "alpaca", "vicuña",
           "alce", "oso", "panda", "koala", "canguro", "wallaby", "koala", "diablo de Tasmania", "wombat",
           "numbat", "perezoso", "armadillo", "oso hormiguero", "osito", "mapache", "tejón", "comadreja", "ardilla",
            "castor"]

letras = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'Ñ', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V','W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'ñ', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
